[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
platform_packages =
    platformio/framework-arduinoespressif8266@3.30102.0
    platformio/toolchain-xtensa@2.100300.220621
    platformio/tool-esptool@1.413.0
    platformio/tool-esptoolpy@1.30000.201119
monitor_speed = 115200
upload_protocol = esptool
lib_deps =
    https://github.com/bblanchon/ArduinoJson.git#1cd478f48e7c4cd142a0bd26ee17d63d70d04e3f
    https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot.git#601a1f45556409cf45781bf2ddfb8a36f5bf8829

[env:nodemcuv2_ota]
extends = env:nodemcuv2
upload_protocol = espota

[env:nodemcuv2_ci]
extends = env:nodemcuv2
build_src_filter = +<*> -<infrastructure/env.cpp>
extra_scripts = post:scripts/ci_config.py

[env:native]
platform = native@1.2.1
test_framework = unity
lib_deps =
    https://github.com/bblanchon/ArduinoJson.git#1cd478f48e7c4cd142a0bd26ee17d63d70d04e3f
    throwtheswitch/Unity@2.6.1
test_build_src = true
build_flags = -std=c++17 -Wall -Wextra -Werror -Itest/fakes
build_src_filter = -<*> +<application/*.cpp> +<presentation/EventNotifier.cpp> +<infrastructure/telegram/HttpResponse.cpp> +<infrastructure/telegram/TelegramAcknowledgement.cpp> +<infrastructure/telegram/TelegramConnection.cpp> +<infrastructure/settings/SettingsStore.cpp>
