#ifndef LIGHTONNOTIFIER_INFRASTRUCTURE_WEB_WEBPAGE_H
#define LIGHTONNOTIFIER_INFRASTRUCTURE_WEB_WEBPAGE_H

#include <pgmspace.h>

static const char WEB_PAGE[] PROGMEM = R"html(<!doctype html>
<html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>LightOnNotifier</title><link rel="stylesheet" href="/app.css"></head><body>
<header><div class="wrap"><strong>LightOnNotifier</strong><span id="connection">Підключення…</span></div></header>
<main class="wrap">
<section id="login" class="card"><h1>Вхід до пристрою</h1><p>Введіть пароль адміністратора або секрет початкового налаштування.</p>
<form id="loginForm"><label>Пароль <input name="password" type="password" autocomplete="current-password" required></label><button>Увійти</button></form></section>
<div id="app" hidden>
<nav aria-label="Розділи"><button data-tab="state" class="selected">Стан</button><button data-tab="signals">Звук і світлодіод</button><button data-tab="wifi">Wi-Fi</button><button data-tab="telegram">Telegram</button><button data-tab="device">Пристрій</button></nav>
<section id="state" class="card panel"><h1>Стан пристрою</h1><div id="statusGrid" class="grid"></div><h2>Одержувачі</h2><div id="recipientStatus"></div><h2>Тестове повідомлення</h2><p>Надсилання створить окреме повідомлення «Тест: …». Довгий текст тесту скорочується до 512 байтів. Якщо відповідь загубиться, повтор може створити дублікат.</p><div id="testRecipients"></div><button id="testButton" type="button">Надіслати тестове повідомлення</button><div id="testStatus"></div></section>
<section id="signals" class="card panel" hidden><h1>Звук і світлодіод</h1><form id="signalsForm">
<fieldset><legend>Звук</legend><label class="check"><input type="checkbox" name="startupSound"> Звук при появі світла</label><label class="check"><input type="checkbox" name="wifiProgressSound"> Звук під час підключення до Wi-Fi</label><label class="check"><input type="checkbox" name="wifiConnectedSound"> Звук після підключення до Wi-Fi</label><small>Під час тривалої мережевої операції звук може закінчитися пізніше.</small></fieldset>
<fieldset><legend>Зовнішній світлодіод</legend><label class="check"><input type="checkbox" name="ledEnabled"> Використовувати світлодіод</label><label class="check"><input type="checkbox" name="deliveryBlink"> Індикація успішного надсилання</label>
<label>При появі світла <select name="startupLed"></select></label><label>Підключення до Wi-Fi <select name="connectingLed"></select></label><label>Очікування надсилання <select name="waitingLed"></select></label><label>Звичайна робота <select name="idleLed"></select></label><label>Помилка <select name="errorLed"></select></label></fieldset><div class="actions"><button>Зберегти</button><button type="button" class="secondary cancel">Скасувати зміни</button></div></form><p class="hint">Звичайна робота починається після завершення запуску й підтвердження доставки всім одержувачам.</p><div id="previewControls"><h2>Попередній перегляд</h2><label>Режим світлодіода для перегляду <select id="previewMode"><option value="0">Вимкнено</option><option value="1">Світиться постійно</option><option value="2">Блимає</option></select></label><button type="button" data-preview="startup">Стартовий звук</button><button type="button" data-preview="connecting">Wi-Fi: підключення</button><button type="button" data-preview="connected">Wi-Fi: успіх</button><button type="button" data-preview="led">Світлодіод</button></div></section>
<section id="wifi" class="card panel" hidden><h1>Wi-Fi</h1><p>Зміна мережі може роз’єднати браузер. Якщо нову адресу не підтвердити за 120 секунд, пристрій поверне старі налаштування.</p><form id="wifiForm"><label>Назва мережі (SSID) <input name="ssid" maxlength="32" required></label><label>Новий пароль Wi-Fi <input name="password" type="password" maxlength="64" autocomplete="new-password" placeholder="Залиште порожнім, щоб не змінювати"></label><label class="check"><input name="openNetwork" type="checkbox"> Це відкрита мережа без пароля</label><label>Статична IP-адреса <input name="ip" inputmode="decimal" required></label><label>Шлюз <input name="gateway" inputmode="decimal" required></label><label>Маска підмережі <input name="subnet" inputmode="decimal" required></label><button>Застосувати та перевірити</button></form><div id="wifiPending" hidden><p>Відкрийте пристрій за новою адресою, увійдіть і підтвердьте доступ.</p><a id="newAddress" rel="noreferrer">Відкрити нову адресу</a><button id="confirmWifi" type="button">Підтвердити доступ</button></div></section>
<section id="telegram" class="card panel" hidden><h1>Telegram</h1><p>Зміни застосовуються до наступного запуску та нових явних тестів. Поточне стартове повідомлення зберігає свої дані.</p><form id="telegramForm"><label>Новий токен бота <input name="token" type="password" maxlength="128" autocomplete="off" placeholder="Залиште порожнім, щоб не змінювати"></label><label>Одержувачі, по одному в рядку <textarea name="recipients" rows="8" required></textarea></label><label>Повідомлення при появі світла <textarea name="message" rows="4" required></textarea></label><small id="messageBytes"></small><div class="actions"><button>Зберегти</button><button type="button" class="secondary cancel">Скасувати зміни</button></div></form></section>
<section id="device" class="card panel" hidden><h1>Пристрій</h1><p>Вебінтерфейс працює в довіреній локальній мережі. Через HTTP пароль і дані не шифруються.</p><form id="passwordForm"><label>Новий пароль адміністратора (12–64 байти) <input name="password" type="password" autocomplete="new-password" required></label><button>Змінити пароль</button></form><hr><button id="restart" type="button" class="secondary">Перезапустити пристрій</button><button id="reset" type="button" class="danger">Скинути налаштування</button><p>Перезапуск створить нове стартове повідомлення. Скидання вимкне доставку до повторного налаштування.</p></section>
</div><p id="notice" role="status"></p></main><script src="/app.js" defer></script></body></html>)html";

static const char WEB_STYLE[] PROGMEM =
    R"css(:root{color-scheme:light;font:16px system-ui,-apple-system,sans-serif;background:#f4f7fa;color:#172333}*{box-sizing:border-box}body{margin:0}header{background:#163b57;color:white;padding:16px 0}header .wrap{display:flex;justify-content:space-between;gap:12px}.wrap{max-width:920px;margin:auto;padding:0 16px}main{padding-top:18px;padding-bottom:40px}.card{background:white;border:1px solid #dce5eb;border-radius:12px;padding:22px;margin:18px 0;box-shadow:0 2px 8px #112a3a0a}h1{font-size:1.45rem;margin:0 0 16px}h2{font-size:1.1rem;margin-top:24px}nav{display:flex;gap:8px;flex-wrap:wrap}button{border:0;border-radius:8px;background:#006ca9;color:white;padding:11px 16px;font:inherit;cursor:pointer;min-height:44px}button:hover{filter:brightness(.92)}button:disabled{opacity:.5;cursor:not-allowed}button.secondary{background:#dce7ee;color:#172333}button.danger{background:#b52e3a}nav button{background:#dce7ee;color:#172333}nav button.selected{background:#006ca9;color:white}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}label{display:block;margin:15px 0;font-weight:600}input:not([type=checkbox]),textarea,select{display:block;width:100%;max-width:600px;border:1px solid #9cb0be;border-radius:8px;padding:10px;font:inherit;margin-top:6px}input[type=checkbox]{width:20px;height:20px;vertical-align:middle}.check{font-weight:400}fieldset{border:1px solid #dce5eb;border-radius:9px;margin:16px 0;padding:12px 16px}legend{font-weight:700}small,.hint{color:#4e6070}#notice{min-height:26px;font-weight:600}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.grid>div{padding:12px;background:#eff5f8;border-radius:8px}.grid strong{display:block}#recipientStatus>div,#testRecipients>label{padding:7px 0;border-bottom:1px solid #e8edef;display:block}#previewControls button{margin:3px}a{display:block;margin:12px 0;color:#005d92;overflow-wrap:anywhere}hr{border:0;border-top:1px solid #dce5eb;margin:24px 0}@media(max-width:500px){.card{padding:16px}header .wrap{display:block}#connection{display:block;margin-top:5px}nav button{flex:1 1 45%}})css";

static const char WEB_SCRIPT[] PROGMEM = R"js('use strict';
const $ = s => document.querySelector(s);
let csrf = '', revision = 0, saved = null, dirty = false, refreshTimer;
const labels = {connected:'Підключено',disconnected:'Немає зв’язку',partial:'Частково надіслано',waiting:'Очікування надсилання',delivered:'Надіслано',exhausted:'Спроби вичерпано',invalid:'Неправильна конфігурація',empty:'Немає події'};
function notice(text,error=false){$('#notice').textContent=text;$('#notice').style.color=error?'#a21f2b':'#17613e'}
async function api(path, values){const options={credentials:'same-origin'};if(values){options.method='POST';options.headers={'Content-Type':'application/x-www-form-urlencoded','X-CSRF':csrf};options.body=new URLSearchParams(values)}let response;try{response=await fetch('/api/'+path,options)}catch{throw Error('Немає з’єднання. Перевірте стан пристрою перед повтором дії.')}let data=await response.json();if(!response.ok)throw Error(data.error||'Помилка запиту');return data}
function fields(form){const out={revision:String(revision)};for(const el of form.elements){if(!el.name)continue;out[el.name]=el.type==='checkbox'?(el.checked?'1':'0'):el.value}return out}
function selectedTab(name){for(const p of document.querySelectorAll('.panel'))p.hidden=p.id!==name;for(const b of document.querySelectorAll('nav button'))b.classList.toggle('selected',b.dataset.tab===name)}
function setForm(form,data,names){for(const name of names){const el=form.elements[name];if(el)el.type==='checkbox'?el.checked=!!data[name]:el.value=data[name]??''}}
function populate(data){saved=data;revision=data.revision;setForm($('#signalsForm'),data,['startupSound','wifiProgressSound','wifiConnectedSound','ledEnabled','deliveryBlink','startupLed','connectingLed','waitingLed','idleLed','errorLed']);setForm($('#wifiForm'),data,['ssid','ip','gateway','subnet']);$('#wifiForm').elements.password.value='';$('#wifiForm').elements.openNetwork.checked=false;$('#telegramForm').elements.recipients.value=data.recipients.join('\n');$('#telegramForm').elements.message.value=data.message;$('#telegramForm').elements.token.value='';$('#newAddress').href='http://'+data.ip+'/';$('#newAddress').textContent='Відкрити '+data.ip;bytes();dirty=false}
function bytes(){let n=new TextEncoder().encode($('#telegramForm').elements.message.value).length;$('#messageBytes').textContent=n+' / 512 байтів';$('#messageBytes').style.color=n>512?'#a21f2b':''}
async function refreshSettings(){populate(await api('settings'))}
function statusCell(name,value){const box=document.createElement('div');const key=document.createElement('strong');key.textContent=name;box.append(key,document.createTextNode(value));return box}
async function refreshStatus(){try{let s=await api('status');$('#connection').textContent=s.wifi==='connected'?'Wi-Fi підключено':'Немає Wi-Fi';let g=$('#statusGrid');g.replaceChildren(statusCell('Wi-Fi',labels[s.wifi]),statusCell('IP-адреса',s.ip||'—'),statusCell('Час',s.timeReady?'Готовий':'Очікування NTP'),statusCell('Доставка',labels[s.delivery]||s.delivery),statusCell('Світлодіод',s.ledActive?'Світиться':'Вимкнений'),statusCell('Зумер',s.buzzerActive?'Звучить':'Мовчить'),statusCell('Час роботи',Math.floor(s.uptimeMs/60000)+' хв'),statusCell('Прошивка',s.firmware),statusCell('Збереження',s.storageReady?'Готове':'Недоступне'),statusCell('Конфігурація',s.unsupportedSchema?'Непідтримувана версія':s.configured?'Налаштована':'Потрібне налаштування'));$('#recipientStatus').replaceChildren(...s.recipients.map(r=>{let d=document.createElement('div');d.textContent='Одержувач №'+(r.index+1)+': '+(labels[r.outcome]||r.outcome)+'; спроб: '+r.attempts;return d}));$('#testStatus').textContent=s.testActive?'Тест триває':s.tests.map((v,i)=>v?'№'+(i+1)+': '+(v===1?'надіслано':'помилка'):'').filter(Boolean).join('; ');$('#testButton').disabled=s.testActive||!s.timeReady||s.wifi!=='connected'||!['delivered','exhausted'].includes(s.delivery);$('#wifiPending').hidden=!s.wifiPending;$('#confirmWifi').disabled=s.wifi!=='connected';if($('#testRecipients').children.length!==(saved?.recipients||[]).length)$('#testRecipients').replaceChildren(...(saved?.recipients||[]).map((_,i)=>{let l=document.createElement('label');let c=document.createElement('input');c.type='checkbox';c.value=i;c.checked=true;l.append(c,document.createTextNode(' Одержувач №'+(i+1)));return l}));if(s.wifiPending)notice('Підтвердьте доступ із нової адреси протягом 120 секунд.');else if(!dirty)notice('')}catch(e){$('#connection').textContent='Зв’язок втрачено';notice('Дані стану застаріли. '+e.message,true)}}
async function enter(){try{let s=await api('session');csrf=s.csrf;$('#login').hidden=true;$('#app').hidden=false;await refreshSettings();await refreshStatus();if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(refreshStatus,5000)}catch{$('#login').hidden=false;$('#app').hidden=true}}
for(const select of document.querySelectorAll('#signals select')){for(const [value,label] of [['0','Вимкнено'],['1','Світиться постійно'],['2','Блимає']])select.add(new Option(label,value))}
for(const b of document.querySelectorAll('nav button'))b.addEventListener('click',()=>selectedTab(b.dataset.tab));
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const response=await api('login',{password:e.target.elements.password.value});csrf=response.csrf;await enter()}catch(err){notice(err.message,true)}});
for(const f of document.querySelectorAll('#app form'))f.addEventListener('input',()=>{dirty=true;if(f.id==='telegramForm')bytes()});
for(const b of document.querySelectorAll('.cancel'))b.addEventListener('click',()=>{populate(saved);notice('Зміни скасовано')});
$('#signalsForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('signals',fields(e.target));await refreshSettings();notice('Збережено')}catch(err){notice(err.message,true)}});
$('#telegramForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('telegram',fields(e.target));await refreshSettings();notice('Збережено. Зміни події діятимуть після наступного запуску.')}catch(err){notice(err.message,true)}});
$('#wifiForm').addEventListener('submit',async e=>{e.preventDefault();if(!confirm('Зміна Wi-Fi може роз’єднати браузер. Застосувати?'))return;const v=fields(e.target);try{await api('wifi',v);$('#newAddress').href='http://'+v.ip+'/';$('#newAddress').textContent='Відкрити '+v.ip;$('#wifiPending').hidden=false;dirty=false;notice('Перейдіть за новою адресою та підтвердьте доступ.')}catch(err){notice(err.message,true)}});
$('#confirmWifi').addEventListener('click',async()=>{try{await api('wifi/confirm',{revision:String(revision)});await refreshSettings();await refreshStatus();notice('Нові мережеві параметри збережено')}catch(err){notice(err.message,true)}});
$('#passwordForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('password',fields(e.target));notice('Пароль змінено. Увійдіть знову.');$('#app').hidden=true;$('#login').hidden=false}catch(err){notice(err.message,true)}});
$('#testButton').addEventListener('click',async()=>{let mask=0;for(const c of document.querySelectorAll('#testRecipients input:checked'))mask|=1<<Number(c.value);if(!mask||!confirm('Надіслати тестове повідомлення вибраним одержувачам?'))return;try{await api('test',{mask:String(mask)});notice('Тест поставлено в чергу');await refreshStatus()}catch(err){notice(err.message,true)}});
for(const b of document.querySelectorAll('[data-preview]'))b.addEventListener('click',async()=>{try{let mode=$('#previewMode').value;let soundField={startup:'startupSound',connecting:'wifiProgressSound',connected:'wifiConnectedSound'}[b.dataset.preview];let enabled=soundField?$('#signalsForm').elements[soundField].checked:'1';await api('preview',{kind:b.dataset.preview,mode,enabled:enabled?'1':'0'});notice('Попередній перегляд запущено')}catch(err){notice(err.message,true)}});
$('#restart').addEventListener('click',async()=>{if(!confirm('Перезапуск створить нове стартове повідомлення. Продовжити?'))return;try{await api('restart',{});notice('Пристрій перезапускається')}catch(err){notice(err.message,true)}});
$('#reset').addEventListener('click',async()=>{if(!confirm('Скинути всі збережені налаштування? Доставка зупиниться до нового налаштування.'))return;try{await api('reset',{revision:String(revision)});notice('Налаштування скинуто. Увійдіть із секретом початкового доступу.');$('#app').hidden=true;$('#login').hidden=false}catch(err){notice(err.message,true)}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
enter();
)js";

#endif
